version: 0.0
os: linux

files:
  - source: mavve/src/main/resources/application.yml
    destination: /home/ubuntu/MAVVE-back/mavve/src/main/resources/
    overwrite: yes
  
  - source: build/libs/
    destination: /home/ubuntu/MAVVE-back/build/libs
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu