spring:
  application:
    name: mavve
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    stack:
      auto: false
spotify:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  redirect-uri: http://127.0.0.1:8080/login/oauth2/code/spotify
  auth-uri: https://accounts.spotify.com/authorize
  token-uri: https://accounts.spotify.com/api/token
  user-info-uri: https://api.spotify.com/v1/me
  search-uri: https://api.spotify.com/v1/search
  get-track-uri: https://api.spotify.com/v1/tracks
server:
  tomcat:
    uri-encoding: UTF-8
