spring:
  application:
    name: mavve
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
kakao:
  token:
    uri: ${KAKAO_TOKEN_URI}
  client:
    id: ${CLIENT_ID}
  user:
    info:
      uri: ${KAKAO_USER_INFO_URI}
  redirect:
    uri: ${KAKAO_REDIRECT_URI}

youtube:
  api:
    key: ${YOUTUBE_KEY}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    stack:
      auto: false
