package com.efub.mavve.global.exception;

public enum ClientExceptionCode {
    LOGIN_ERROR,
    AUTH_SERVER_ERROR,
    AUTH_TOKEN_EMPTY,
    ACCESS_TOKEN_EMPTY,
    REFRESH_TOKEN_EMPTY,
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_INVALID,
    AUTH_TOKEN_MISMATCH,
    USER_NOT_FOUND,
    ILLEGAL_ARGUMENT,
    INTERNAL_SERVER_ERROR,

    DIARY_NOT_FOUND,
    ROOM_NOT_FOUND,
    SONG_NOT_FOUND,
    ARTIST_NOT_FOUND,
    SONG_LIST_EMPTY,
    ILLEGAL_PAGE_NUMBER,
    ILLEGAL_PAGE_SIZE,
    SONG_RESULT_NOT_FOUND,

    PLAYLIST_NOT_FOUND,
    TITLE_ALREADY_EXIST,

    IMAGE_UPLOAD_FAILED,
    NO_FILE_PROVIDED,
    INVALID_IMAGE_EXTENSION,

    REDIS_SAVE_ERROR,
    REDIS_DELETE_ERROR,
    REDIS_DESERIALIZATION_ERROR,

    ROOM_OWNER_MISMATCH,
}
